### ISSUE TITLE
Last update breaks app

### ISSUE THREAD

**Issue by theanimal666** [brianc/node-pg-types#34]
Hi,

I've no idea why but the update from 1.7.0 to 1.8.0 breaks my app with the following error message:

	Array.parseBigIntegerArray (/app/api/node_modules/bub-backend-shared/node_modules/pg/node_modules/pg-types/lib/textParsers.js:32:22)
	new eval (eval at <anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/result.js:98:20), <anonymous>:28:73)
	Result.parseRow (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/result.js:61:10)
	Query.handleDataRow (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/query.js:58:26)
	null.<anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/client.js:108:24)
	emit (events.js:107:17)
	Socket.<anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/connection.js:109:12)
	Socket.emit (events.js:107:17)
	readableAddChunk (_stream_readable.js:163:16)
	Socket.Readable.push (_stream_readable.js:126:10)
	TCP.onread (net.js:538:20)
	Uncaught ReferenceError: val is not defined

	FROM
	Array.parseBigIntegerArray (/app/api/node_modules/bub-backend-shared/node_modules/pg/node_modules/pg-types/lib/textParsers.js:32:22)
	new eval (eval at <anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/result.js:98:20), <anonymous>:28:73)
	Result.parseRow (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/result.js:61:10)
	Query.handleDataRow (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/query.js:58:26)
	null.<anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/client.js:108:24)
	emit (events.js:107:17)
	Socket.<anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/connection.js:109:12)
	Socket.emit (events.js:107:17)
	readableAddChunk (_stream_readable.js:163:16)
	Socket.Readable.push (_stream_readable.js:121:15)
	TCP.onread (net.js:538:20)
	Uncaught ReferenceError: val is not defined

	FROM
	Array.parseBigIntegerArray (/app/api/node_modules/bub-backend-shared/node_modules/pg/node_modules/pg-types/lib/textParsers.js:32:22)
	new eval (eval at <anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/result.js:98:20), <anonymous>:28:73)
	Result.parseRow (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/result.js:61:10)
	Query.handleDataRow (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/query.js:58:26)
	null.<anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/client.js:108:24)
	emit (events.js:107:17)
	Socket.<anonymous> (/app/api/node_modules/bub-backend-shared/node_modules/pg/lib/connection.js:109:12)
	Socket.emit (events.js:107:17)
	readableAddChunk (_stream_readable.js:163:16)
	Socket.Readable.push (_stream_readable.js:126:10)
	TCP.onread (net.js:538:20)

**Comment by wejendorp** [comment]
I think there's an issue with arrays in this release:
```
TypeError: Cannot read property 'length' of undefined
  at ArrayParser.isEof (/usr/src/app/node_modules/pg/node_modules/pg-types/node_modules/postgres-array/index.js:17:38)
  at ArrayParser.parse (/usr/src/app/node_modules/pg/node_modules/pg-types/node_modules/postgres-array/index.js:53:16)
  at Object.exports.parse (/usr/src/app/node_modules/pg/node_modules/pg-types/node_modules/postgres-array/index.js:4:45)
  at Array.parseStringArray (/usr/src/app/node_modules/pg/node_modules/pg-types/lib/textParsers.js:53:12)
  at new eval (eval at <anonymous> (/usr/src/app/node_modules/pg/lib/result.js:98:20), <anonymous>:14:73)
  at [object Object].Result.parseRow (/usr/src/app/node_modules/pg/lib/result.js:61:10)
  at [object Object].Query.handleDataRow (/usr/src/app/node_modules/pg/lib/query.js:58:26)
  at [object Object].<anonymous> (/usr/src/app/node_modules/pg/lib/client.js:108:24)
  at emitOne (events.js:77:13)
  at [object Object].emit (events.js:169:7)
  at Socket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:109:12)
  at emitOne (events.js:77:13)
  at Socket.emit (events.js:169:7)
  at readableAddChunk (_stream_readable.js:146:16)
  at Socket.Readable.push (_stream_readable.js:110:10)
  at TCP.onread (net.js:521:20) 
```

**Comment by marekventur** [comment]
Same here, problems with parsing arrays.

I think the problem is here: https://github.com/brianc/node-pg-types/commit/f0c931a3c9d034fc3bf9ffa32c05784629ab38aa#diff-0c09eb4a798638a9038dbb1e605d8138R4

working on a patch right now.

**Comment by marekventur** [comment]
This seems to solve the problem for me: https://github.com/brianc/node-pg-types/pull/35

**Comment by JulienWeiler** [comment]
Same problem here. The fix from @marekventur works for me as well

**Comment by dgrelaud** [comment]
Same problem here.

**Comment by Lesterpig** [comment]
Same here , thanks @marekventur for the patch!

**Comment by FlorianBezagu** [comment]
:+1:

**Comment by EtienneRd** [comment]
Same here, thanks for the patch @marekventur

**Comment by Nightmare53** [comment]
:+1:

**Comment by jucrouzet** [comment]
:+1:

**Comment by brianc** [comment]
Thanks to the quick work of @marekventur this was fixed before I even woke up in the morning. :dancer:  I apologize for that one slipping through.  New version with fix published at `pg-types@1.9.0`

**Comment by crdeutsch** [comment]
Can we get a version bump to `pg-types` so we don't have to fork it and `pg` will start working?

**Comment by brianc** [comment]
Already published the version with the fix 4 days ago.

```
 
{ name: 'pg-types',
  description: 'Query result type converters for node-postgres',
  'dist-tags': { latest: '1.9.0' },
  versions: 
   [ '1.0.0',
     '1.1.0',
     '1.2.0',
     '1.3.0',
     '1.4.0',
     '1.5.0',
     '1.6.0',
     '1.7.0',
     '1.8.0',
     '1.9.0' ],
  maintainers: 'brianc <brian.m.carlson@gmail.com>',
  time: 
   { modified: '2015-07-30T13:42:36.046Z',
     created: '2014-03-15T20:34:58.912Z',
     '1.0.0': '2014-03-15T20:34:58.912Z',
     '1.1.0': '2014-05-12T13:41:28.601Z',
     '1.2.0': '2014-05-12T13:50:03.137Z',
     '1.3.0': '2014-06-04T13:55:26.129Z',
     '1.4.0': '2014-07-13T16:27:28.660Z',
     '1.5.0': '2014-10-01T18:34:03.862Z',
     '1.6.0': '2014-10-15T19:33:38.127Z',
     '1.7.0': '2015-02-21T15:57:53.587Z',
     '1.8.0': '2015-07-30T04:17:38.586Z',
     '1.9.0': '2015-07-30T13:42:36.046Z' },
  homepage: 'https://github.com/brianc/node-pg-types',
  keywords: [ 'postgres', 'PostgreSQL', 'pg' ],
  repository: 
   { type: 'git',
     url: 'git://github.com/brianc/node-pg-types.git' },
  author: 'Brian M. Carlson',
  bugs: { url: 'https://github.com/brianc/node-pg-types/issues' },
  license: 'MIT',
  readmeFilename: 'README.md',
  version: '1.9.0',
  main: 'index.js',
  scripts: { test: 'tape test/*.js | tap-spec' },
  devDependencies: { pff: '^1.0.0', 'tap-spec': '^4.0.0', tape: '^4.0.0' },
  dependencies: 
   { ap: '~0.2.0',
     'postgres-array': '~1.0.0',
     'postgres-bytea': '~1.0.0',
     'postgres-date': '~1.0.0',
     'postgres-interval': '~1.0.0' },
  gitHead: '4cbcb893747aa31028d264662637dbda5fd29d67',
  dist: 
   { shasum: 'dfea2d096f905ae438a069b2dd8ac35a613d39e7',
     tarball: 'http://registry.npmjs.org/pg-types/-/pg-types-1.9.0.tgz' },
  directories: {} }

```

**Comment by crdeutsch** [comment]
@brianc you bumped the version `after` you applied the fix.

do an `npm install` it's still broken

**Comment by crdeutsch** [comment]
Maybe I misread what this bug is.

But this is the fix I needed because currently `val is not defined`
https://github.com/brianc/node-pg-types/commit/6e0865b14d82949014a853e1ca9a4c2c4c00ed61#diff-2f6fa2abb37db873140607da44255c50L32

**Comment by brianc** [comment]
Yah different bug....I'll push a new version now.

**Comment by brianc** [comment]
```

npm version minor -m "Bump version"
v1.10.0
git push origin master --tags
Counting objects: 4, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 423 bytes | 0 bytes/s, done.
Total 4 (delta 2), reused 0 (delta 0)
To git@github.com:brianc/node-pg-types.git
   9d4d6aa..b29fd45  master -> master
 * [new tag]         v1.10.0 -> v1.10.0
npm publish
+ pg-types@1.10.0
```

**Comment by crdeutsch** [comment]
Working now. Thanks for the fast response!!

**Comment by brianc** [comment]
No problemo! Glad it's fixed

**Comment by theanimal666** [comment]
:+1: thanks
